"""initial-6

Revision ID: a94f7885f366
Revises: 
Create Date: 2021-11-25 20:11:16.992938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94f7885f366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewcard', schema=None) as batch_op:
        batch_op.create_unique_constraint('_review_respose_card_uc', ['card_id', 'review_respose_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewcard', schema=None) as batch_op:
        batch_op.drop_constraint('_review_respose_card_uc', type_='unique')

    # ### end Alembic commands ###
